name: Cron

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  fetch_calendar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.3'

    - name: Check calendar updates
      env:
        GH_BEARER: ${{ secrets.GH_BEARER }}
        GH_GIST: ${{ secrets.GH_GIST }}
      run: ./cron.sh
